server:
  port: 8000
eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，本身就是所以无需注册
    fetchRegistry: false  #是否从Eureka中获取注册信息
    serviceUrl:
      defaultZone: http://admin:123456@localhost:${server.port}/eureka/  #Eureka客户端与Eureka服务端进行交互的地址
spring:
  security:
    user:
      name: admin
      password: 123456